# -*- coding: utf-8 -*-
"""distribusi_penjualan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GC6sQTTKtqMr6gn2x9kq7gj3S9zcgMCe
"""

!pip install lime

from google.colab import drive
drive.mount('/content/drive')

"""# Mempersiapkan Data"""

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor, VotingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import lime
import lime.lime_tabular

# Muat dataset versi vscode
# file_path = 'dataset_fix/data_selada.csv'
# df = pd.read_csv(file_path, delimiter=';')
# print("Dataset berhasil dimuat")

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/baru/dataset/data_selada.csv', sep=';')
df.head()

# Bersihkan nama kolom dan hapus kolom Unnamed yang kosong
df.columns = df.columns.str.strip()
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
print("Kolom setelah pembersihan:", df.columns.tolist())
print(df.head())
# df = pd.DataFrame(data)

# Mengisi nilai NaN di kolom 'Pasar' dengan median atau mean
# Untuk tujuan prediksi, kita akan mengisi dengan 0 karena nilai NaN tampaknya menunjukkan 0 penjualan di pasar.
df['Pasar'].fillna(0, inplace=True)

# Definisikan fitur (X) dan target (y)
features = ['Jumlah Tanam', 'Data Stok', 'Data Transaksi']
targets = ['Rumah Sendiri', 'Rt 1', 'Rt 2', 'Rt 3', 'Rt 4', 'Rt 5', 'Rt 6', 'Rt 7', 'Pasar']

X = df[features]
y = df[targets]

# Bagi data menjadi training dan testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data berhasil dimuat dan dibagi.")

"""# Model Random Forest, SVM, dan Voting Regressor untuk Setiap Target Penjualan

"""

# Menghitung metrik evaluasi
def evaluate_model(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    # MAPE: Hindari pembagian dengan nol jika ada nilai y_true yang nol
    # Jika y_true nol dan y_pred nol, maka error adalah 0.
    # Jika y_true nol tapi y_pred tidak nol, maka error bisa tak hingga.
    # Kita akan mengganti nilai tak hingga dengan 0 untuk mencegah crash.
    with np.errstate(divide='ignore', invalid='ignore'):
        percentage_errors = np.abs((y_true - y_pred) / y_true)
        percentage_errors[y_true == 0] = 0 # Jika aktual 0, prediksi 0 -> 0 error. Jika aktual 0, prediksi tidak 0 -> kita tidak menghitung MAPE untuk kasus ini.
        mape = np.mean(percentage_errors) * 100
        mape = mape if not np.isinf(mape) else 0 # Handle cases where y_true is 0, resulting in inf
    return mse, mae, mape

# Dictionary untuk menyimpan model terbaik dan hasil evaluasi
best_models = {}
evaluation_results = {}
predictions_test = {}

# Hyperparameter grids
rf_param_grid = {
    'n_estimators': [100, 200],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2],
    'min_samples_split': [2, 5]
}

svm_param_grid = {
    'C': [0.1, 1, 10],
    'epsilon': [0.01, 0.1],
    'kernel': ['rbf', 'linear']
}

print("\nMemulai pelatihan dan tuning model untuk setiap target penjualan...")

for target in targets:
    print(f"\n--- Melatih model untuk target: {target} ---")
    y_train_target = y_train[target]
    y_test_target = y_test[target]

    # Random Forest Regressor
    rf = RandomForestRegressor(random_state=42)
    rf_grid_search = GridSearchCV(estimator=rf, param_grid=rf_param_grid, cv=5, n_jobs=-1, verbose=0, scoring='neg_mean_squared_error')
    rf_grid_search.fit(X_train, y_train_target)
    best_rf = rf_grid_search.best_estimator_
    best_models[f'rf_{target}'] = best_rf
    rf_predictions = best_rf.predict(X_test)
    rf_mse, rf_mae, rf_mape = evaluate_model(y_test_target, rf_predictions)
    evaluation_results[f'rf_{target}'] = {'MSE': rf_mse, 'MAE': rf_mae, 'MAPE': rf_mape}
    predictions_test[f'rf_{target}'] = rf_predictions
    print(f"  Random Forest - Best Params: {rf_grid_search.best_params_}")
    print(f"  Random Forest - MSE: {rf_mse:.2f}, MAE: {rf_mae:.2f}, MAPE: {rf_mape:.2f}%")

    # Support Vector Regressor (SVR)
    svm = SVR()
    svm_grid_search = GridSearchCV(estimator=svm, param_grid=svm_param_grid, cv=5, n_jobs=-1, verbose=0, scoring='neg_mean_squared_error')
    svm_grid_search.fit(X_train, y_train_target)
    best_svm = svm_grid_search.best_estimator_
    best_models[f'svm_{target}'] = best_svm
    svm_predictions = best_svm.predict(X_test)
    svm_mse, svm_mae, svm_mape = evaluate_model(y_test_target, svm_predictions)
    evaluation_results[f'svm_{target}'] = {'MSE': svm_mse, 'MAE': svm_mae, 'MAPE': svm_mape}
    predictions_test[f'svm_{target}'] = svm_predictions
    print(f"  SVM - Best Params: {svm_grid_search.best_params_}")
    print(f"  SVM - MSE: {svm_mse:.2f}, MAE: {svm_mae:.2f}, MAPE: {svm_mape:.2f}%")

    # Voting Regressor
    voting_regressor = VotingRegressor(estimators=[('rf', best_rf), ('svm', best_svm)], n_jobs=-1)
    voting_regressor.fit(X_train, y_train_target)
    best_models[f'voting_{target}'] = voting_regressor
    voting_predictions = voting_regressor.predict(X_test)
    voting_mse, voting_mae, voting_mape = evaluate_model(y_test_target, voting_predictions)
    evaluation_results[f'voting_{target}'] = {'MSE': voting_mse, 'MAE': voting_mae, 'MAPE': voting_mape}
    predictions_test[f'voting_{target}'] = voting_predictions
    print(f"  Voting Regressor - MSE: {voting_mse:.2f}, MAE: {voting_mae:.2f}, MAPE: {voting_mape:.2f}%")

print("\nPelatihan model selesai.")

"""# Melihat Hasil Prediksi vs Aktual secara Rinci"""

print("\n--- Hasil Prediksi vs Aktual (Sample Test Set) ---")
for target in targets:
    print(f"\nTarget: {target}")
    temp_df = pd.DataFrame({
        'Actual': y_test[target],
        'RF Predicted': predictions_test[f'rf_{target}'],
        'SVM Predicted': predictions_test[f'svm_{target}'],
        'Voting Predicted': predictions_test[f'voting_{target}']
    })
    print(temp_df)

"""# Visualisasi Hasil Prediksi untuk Periode ke-53

"""

# Membuat data untuk prediksi periode ke-53
# Asumsikan nilai untuk periode 53 adalah rata-rata dari 5 periode terakhir yang relevan (Periode 47-52)
last_5_periods = df.tail(5)
new_data_53 = pd.DataFrame({
    'Jumlah Tanam': [last_5_periods['Jumlah Tanam'].mean()],
    'Data Stok': [last_5_periods['Data Stok'].mean()],
    'Data Transaksi': [last_5_periods['Data Transaksi'].mean()]
})

predictions_53_rf = {}
predictions_53_svm = {}
predictions_53_voting = {}

for target in targets:
    # Prediksi menggunakan Random Forest
    pred_rf = best_models[f'rf_{target}'].predict(new_data_53)[0]
    predictions_53_rf[target] = max(0, round(pred_rf))

    # Prediksi menggunakan SVM
    pred_svm = best_models[f'svm_{target}'].predict(new_data_53)[0]
    predictions_53_svm[target] = max(0, round(pred_svm))

    # Prediksi menggunakan Voting Regressor
    pred_voting = best_models[f'voting_{target}'].predict(new_data_53)[0]
    predictions_53_voting[target] = max(0, round(pred_voting))

# Ambil data aktual dari 5 periode terakhir untuk perbandingan visual
actual_avg_last_5_periods = df[targets].tail(5).mean()
bar_positions = np.arange(len(targets))
bar_width = 0.35

# Output dan Visualisasi Random Forest
print(f"\n--- Prediksi Random Forest untuk Periode ke-53 ---")
for target in targets:
    print(f"{target}: {predictions_53_rf[target]}")

plt.figure(figsize=(15, 8))
plt.bar(bar_positions - bar_width/2, actual_avg_last_5_periods.values, bar_width, label='Rata-rata Aktual (5 Periode Terakhir)', color='skyblue')
plt.bar(bar_positions + bar_width/2, list(predictions_53_rf.values()), bar_width, label='Prediksi Periode 53 (Random Forest)', color='lightgreen')
plt.xlabel('Saluran Penjualan')
plt.ylabel('Jumlah Penjualan')
plt.title('Rata-rata Distribusi Penjualan Aktual vs Prediksi Periode 53 - Random Forest')
plt.xticks(bar_positions, targets, rotation=45, ha='right')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Output dan Visualisasi SVM
print(f"\n--- Prediksi SVM untuk Periode ke-53 ---")
for target in targets:
    print(f"{target}: {predictions_53_svm[target]}")

plt.figure(figsize=(15, 8))
plt.bar(bar_positions - bar_width/2, actual_avg_last_5_periods.values, bar_width, label='Rata-rata Aktual (5 Periode Terakhir)', color='skyblue')
plt.bar(bar_positions + bar_width/2, list(predictions_53_svm.values()), bar_width, label='Prediksi Periode 53 (SVM)', color='orange')
plt.xlabel('Saluran Penjualan')
plt.ylabel('Jumlah Penjualan')
plt.title('Rata-rata Distribusi Penjualan Aktual vs Prediksi Periode 53 - SVM')
plt.xticks(bar_positions, targets, rotation=45, ha='right')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Output dan Visualisasi Voting Regressor
print(f"\n--- Prediksi Voting Regressor untuk Periode ke-53 ---")
for target in targets:
    print(f"{target}: {predictions_53_voting[target]}")

plt.figure(figsize=(15, 8))
plt.bar(bar_positions - bar_width/2, actual_avg_last_5_periods.values, bar_width, label='Rata-rata Aktual (5 Periode Terakhir)', color='skyblue')
plt.bar(bar_positions + bar_width/2, list(predictions_53_voting.values()), bar_width, label='Prediksi Periode 53 (Voting Regressor)', color='lightcoral')
plt.xlabel('Saluran Penjualan')
plt.ylabel('Jumlah Penjualan')
plt.title('Rata-rata Distribusi Penjualan Aktual vs Prediksi Periode 53 - Voting Regressor')
plt.xticks(bar_positions, targets, rotation=45, ha='right')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()



"""# LIME"""

# LIME Explanations
# Inisialisasi LIME Explainer
explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_train.values,
    feature_names=X_train.columns.tolist(),
    class_names=targets, # Gunakan nama target untuk multi-output
    mode='regression'
 )

# Pilih satu instance dari X_test untuk dijelaskan
idx_to_explain = 0
instance_to_explain = X_test.iloc[idx_to_explain].values

print(f"\n--- Penjelasan LIME untuk Instance ke-{idx_to_explain + 1} (Periode {X_test.index[idx_to_explain]}) ---")
print(f"Fitur untuk Instance ini: {X_test.iloc[idx_to_explain].to_dict()}")

# Untuk setiap target, jelaskan prediksi menggunakan Voting Regressor (model gabungan)
for target in targets:
    print(f"\nPenjelasan untuk Target: {target}")
    # Karena predict_fn Lime mengharapkan model single-output, kita akan menggunakan model Voting Regressor yang telah dilatih secara individual untuk setiap target.
    model_to_explain = best_models[f'voting_{target}']

    exp = explainer.explain_instance(
        data_row=instance_to_explain,
        predict_fn=lambda x: model_to_explain.predict(pd.DataFrame(x, columns=X_train.columns)),
        num_features=len(features)
    )
    predicted_val = model_to_explain.predict(pd.DataFrame([instance_to_explain], columns=X_train.columns))[0]
    actual_val = y_test.iloc[idx_to_explain][target]
    print(f"  Prediksi Voting Regressor: {predicted_val:.2f}, Aktual: {actual_val}")
    print("  Kontribusi Fitur:")
    for feature, weight in exp.as_list():
        print(f"    - {feature}: {weight:.2f}")

    # Visualisasi penjelasan LIME
    fig = exp.as_pyplot_figure()
    fig.set_size_inches(10, 6)
    plt.title(f'LIME Explanation for {target} (Actual: {actual_val}, Predicted: {predicted_val:.2f})')
    plt.tight_layout()
    plt.show()

# Penjelasan LIME untuk Prediksi Periode ke-53
print(f"\n--- Penjelasan LIME untuk Prediksi Periode ke-53 ---")
print(f"Fitur yang Digunakan untuk Periode 53: {new_data_53.iloc[0].to_dict()}")

for target in targets:
    print(f"\nPenjelasan untuk Target: {target} (Prediksi: {predictions_53_voting[target]}) ")
    model_to_explain = best_models[f'voting_{target}']

    exp_53 = explainer.explain_instance(
        data_row=new_data_53.iloc[0].values,
        predict_fn=lambda x: model_to_explain.predict(pd.DataFrame(x, columns=X_train.columns)),
        num_features=len(features)
    )
    print("  Kontribusi Fitur:")
    for feature, weight in exp_53.as_list():
        print(f"    - {feature}: {weight:.2f}")

    # Visualisasi penjelasan LIME untuk periode ke-53
    fig_53 = exp_53.as_pyplot_figure()
    fig_53.set_size_inches(10, 6)
    plt.title(f'LIME Explanation for {target} (Predicted: {predictions_53_voting[target]:.2f}) - Period 53')
    plt.tight_layout()
    plt.show()