# -*- coding: utf-8 -*-
"""jumlah_tanam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5tlRz8VVo2yP0EGfq6BkwKWK6cP6Ig-
"""

!pip install lime

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor, VotingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import lime
import lime.lime_tabular

# Muat dataset versi vscode
# file_path = 'dataset_fix/data_selada.csv'
# df = pd.read_csv(file_path, delimiter=';')
# print("Dataset berhasil dimuat")

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/baru/dataset/data_selada.csv', sep=';')
df.head()




# Bersihkan nama kolom dan hapus kolom Unnamed yang kosong
df.columns = df.columns.str.strip()
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
print("Kolom setelah pembersihan:", df.columns.tolist())
print(df.head())
# df = pd.DataFrame(data)

# Mengisi nilai NaN di kolom 'Pasar' dengan median atau mean
# Untuk tujuan prediksi, kita akan mengisi dengan 0 karena nilai NaN tampaknya menunjukkan 0 penjualan di pasar.
# df['Pasar'].fillna(0, inplace=True)

# Definisikan fitur (X) dan target (y)
features = ['Data Stok', 'Data Transaksi','Sudah Packing', 'Stok Belum Panen']
X = df[features]
y = df['Jumlah Tanam']

# Bagi data menjadi training dan testing set
# Kita akan menggunakan train_test_split dengan stratifikasi jika targetnya kategorikal, tetapi di sini regresi.
# Random_state digunakan agar hasil selalu sama setiap kali kode dijalankan.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data berhasil dimuat dan dibagi.")

# Random Forest Regressor
rf = RandomForestRegressor(random_state=42)
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [10, 20, 30, None],
    'min_samples_leaf': [1, 2, 4],
    'min_samples_split': [2, 5, 10]
}
rf_grid_search = GridSearchCV(estimator=rf, param_grid=rf_param_grid, cv=5, n_jobs=-1, verbose=1, scoring='neg_mean_squared_error')
rf_grid_search.fit(X_train, y_train)
best_rf = rf_grid_search.best_estimator_

print(f"Best parameters for Random Forest: {rf_grid_search.best_params_}")

# Prediksi dan evaluasi Random Forest
rf_predictions = best_rf.predict(X_test)

# Menghitung metrik evaluasi
def evaluate_model(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    # MAPE: Hindari pembagian dengan nol jika ada nilai y_true yang nol
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    mape = mape if not np.isinf(mape) else 0 # Handle cases where y_true is 0, resulting in inf
    return mse, mae, mape

rf_mse, rf_mae, rf_mape = evaluate_model(y_test, rf_predictions)
print(f"Random Forest - MSE: {rf_mse:.2f}, MAE: {rf_mae:.2f}, MAPE: {rf_mape:.2f}%")

# SVM
svm = SVR()
svm_param_grid = {
    'C': [0.1, 1, 10, 100],
    'epsilon': [0.01, 0.1, 0.5, 1],
    'kernel': ['rbf', 'linear']
}
svm_grid_search = GridSearchCV(estimator=svm, param_grid=svm_param_grid, cv=5, n_jobs=-1, verbose=1, scoring='neg_mean_squared_error')
svm_grid_search.fit(X_train, y_train)
best_svm = svm_grid_search.best_estimator_

print(f"Best parameters for SVM: {svm_grid_search.best_params_}")

# Prediksi dan evaluasi SVM
svm_predictions = best_svm.predict(X_test)
svm_mse, svm_mae, svm_mape = evaluate_model(y_test, svm_predictions)
print(f"SVM - MSE: {svm_mse:.2f}, MAE: {svm_mae:.2f}, MAPE: {svm_mape:.2f}%")

# Voting Regressor
# Menggunakan best_rf dan best_svm dari hasil grid search sebelumnya
voting_regressor = VotingRegressor(estimators=[('rf', best_rf), ('svm', best_svm)], n_jobs=-1)

# Tidak ada grid search untuk voting regressor karena kita menggunakan model terbaik yang sudah di-tuning.
voting_regressor.fit(X_train, y_train)

# Prediksi dan evaluasi Voting Regressor
voting_predictions = voting_regressor.predict(X_test)
voting_mse, voting_mae, voting_mape = evaluate_model(y_test, voting_predictions)
print(f"Voting Regressor - MSE: {voting_mse:.2f}, MAE: {voting_mae:.2f}, MAPE: {voting_mape:.2f}%")

# Data aktual dan prediksi untuk Random Forest
rf_results = pd.DataFrame({'Actual': y_test, 'Predicted': rf_predictions})
print("\nRandom Forest - Actual vs Predicted:")
print(rf_results)

# Data aktual dan prediksi untuk SVM
svm_results = pd.DataFrame({'Actual': y_test, 'Predicted': svm_predictions})
print("\nSVM - Actual vs Predicted:")
print(svm_results)

# Data aktual dan prediksi untuk Voting Regressor
voting_results = pd.DataFrame({'Actual': y_test, 'Predicted': voting_predictions})
print("\nVoting Regressor - Actual vs Predicted:")
print(voting_results)

# Visualisasi perbandingan prediksi vs aktual
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.scatterplot(x=y_test, y=rf_predictions)
plt.title('Random Forest: Actual vs Predicted')
plt.xlabel('Actual Jumlah Tanam')
plt.ylabel('Predicted Jumlah Tanam')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--') # Garis y=x

plt.subplot(1, 3, 2)
sns.scatterplot(x=y_test, y=svm_predictions)
plt.title('SVM: Actual vs Predicted')
plt.xlabel('Actual Jumlah Tanam')
plt.ylabel('Predicted Jumlah Tanam')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--') # Garis y=x

plt.subplot(1, 3, 3)
sns.scatterplot(x=y_test, y=voting_predictions)
plt.title('Voting Regressor: Actual vs Predicted')
plt.xlabel('Actual Jumlah Tanam')
plt.ylabel('Predicted Jumlah Tanam')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--') # Garis y=x

plt.tight_layout()
plt.show()

# Membuat data untuk prediksi periode ke-53
# Asumsikan nilai untuk periode 53 adalah rata-rata dari 5 periode terakhir yang relevan
last_5_periods = df.tail(5) # Ambil 5 baris terakhir dari dataframe
new_data_53 = pd.DataFrame({
    'Data Stok': [last_5_periods['Data Stok'].mean()],
    'Data Transaksi': [last_5_periods['Data Transaksi'].mean()],
    'Sudah Packing': [last_5_periods['Sudah Packing'].mean()],
    'Stok Belum Panen': [last_5_periods['Stok Belum Panen'].mean()]
})

# Prediksi untuk periode ke-53
pred_rf_53 = best_rf.predict(new_data_53)[0]
pred_svm_53 = best_svm.predict(new_data_53)[0]
pred_voting_53 = voting_regressor.predict(new_data_53)[0]

print(f"\nPrediksi Jumlah Tanam untuk Periode ke-53:")
print(f"  Random Forest: {pred_rf_53:.2f}")
print(f"  SVM: {pred_svm_53:.2f}")
print(f"  Voting Regressor: {pred_voting_53:.2f}")


# Menambahkan prediksi ke dataframe untuk visualisasi
df_pred_53 = df.copy()
df_pred_53.loc[len(df_pred_53)] = [53, pred_rf_53, 0, 0, new_data_53['Data Stok'].iloc[0], new_data_53['Sudah Packing'].iloc[0], new_data_53['Stok Belum Panen'].iloc[0], 0, 0, 0, 0, 0, 0, 0, 0, 0, new_data_53['Data Transaksi'].iloc[0], 0] # Isi kolom lain dengan 0 atau nilai default
df_pred_53.loc[len(df_pred_53)-1, 'Jumlah Tanam'] = pred_rf_53 # Update Jumlah Tanam dengan prediksi RF (bisa diganti dengan Voting)

plt.figure(figsize=(12, 6))
plt.plot(df['Periode'], df['Jumlah Tanam'], label='Jumlah Tanam Aktual', marker='o')
plt.plot(df_pred_53['Periode'].iloc[-1], pred_rf_53, 'go', markersize=8, label=f'Prediksi RF Periode 53: {pred_rf_53:.2f}')
plt.plot(df_pred_53['Periode'].iloc[-1], pred_svm_53, 'ro', markersize=8, label=f'Prediksi SVM Periode 53: {pred_svm_53:.2f}')
plt.plot(df_pred_53['Periode'].iloc[-1], pred_voting_53, 'bo', markersize=8, label=f'Prediksi Voting Regressor Periode 53: {pred_voting_53:.2f}')
plt.title('Jumlah Tanam Aktual dan Prediksi untuk Periode ke-53')
plt.xlabel('Periode')
plt.ylabel('Jumlah Tanam')
plt.grid(True)
plt.legend()
plt.show()

# LIME Explanations
# Inisialisasi LIME Explainer
# Pastikan fitur_names sesuai dengan kolom yang digunakan dalam X_train
explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_train.values,
    feature_names=X_train.columns.tolist(),
    class_names=['Jumlah Tanam'], # Untuk regresi, kita bisa menggunakan nama target
    mode='regression'
 )

# Pilih satu instance dari X_test untuk dijelaskan
# Misalnya, instance pertama dari X_test
idx_to_explain = 0
instance_to_explain = X_test.iloc[idx_to_explain].values
actual_value = y_test.iloc[idx_to_explain]

print(f"\nMenjelaskan Prediksi untuk Instance ke-{idx_to_explain + 1} (Periode {X_test.index[idx_to_explain]})")
print(f"Nilai Aktual Jumlah Tanam: {actual_value}")

# Penjelasan untuk Random Forest
exp_rf = explainer.explain_instance(
    data_row=instance_to_explain,
    predict_fn=lambda x: best_rf.predict(pd.DataFrame(x, columns=X_train.columns)),
    num_features=len(features)
 )
print("\nPenjelasan Random Forest:")
pred_rf_instance = best_rf.predict(pd.DataFrame([instance_to_explain], columns=X_train.columns))[0]
print(f"Prediksi RF: {pred_rf_instance:.2f}")
exp_rf.as_list() # Tampilkan penjelasan dalam bentuk list

# Visualisasi penjelasan LIME untuk Random Forest
fig_rf = exp_rf.as_pyplot_figure()
fig_rf.set_size_inches(10, 6)
plt.title(f'LIME Explanation for Random Forest (Actual: {actual_value}, Predicted: {pred_rf_instance:.2f})')
plt.tight_layout()
plt.show()

# Penjelasan untuk SVM
exp_svm = explainer.explain_instance(
    data_row=instance_to_explain,
    predict_fn=lambda x: best_svm.predict(pd.DataFrame(x, columns=X_train.columns)),
    num_features=len(features)
 )
print("\nPenjelasan SVM:")
pred_svm_instance = best_svm.predict(pd.DataFrame([instance_to_explain], columns=X_train.columns))[0]
print(f"Prediksi SVM: {pred_svm_instance:.2f}")
exp_svm.as_list()

# Visualisasi penjelasan LIME untuk SVM
fig_svm = exp_svm.as_pyplot_figure()
fig_svm.set_size_inches(10, 6)
plt.title(f'LIME Explanation for SVM (Actual: {actual_value}, Predicted: {pred_svm_instance:.2f})')
plt.tight_layout()
plt.show()

# Penjelasan untuk Voting Regressor
exp_voting = explainer.explain_instance(
    data_row=instance_to_explain,
    predict_fn=lambda x: voting_regressor.predict(pd.DataFrame(x, columns=X_train.columns)),
    num_features=len(features)
 )
print("\nPenjelasan Voting Regressor:")
pred_voting_instance = voting_regressor.predict(pd.DataFrame([instance_to_explain], columns=X_train.columns))[0]
print(f"Prediksi Voting Regressor: {pred_voting_instance:.2f}")
exp_voting.as_list()

# Visualisasi penjelasan LIME untuk Voting Regressor
fig_voting = exp_voting.as_pyplot_figure()
fig_voting.set_size_inches(10, 6)
plt.title(f'LIME Explanation for Voting Regressor (Actual: {actual_value}, Predicted: {pred_voting_instance:.2f})')
plt.tight_layout()
plt.show()

# Menjelaskan prediksi untuk periode ke-53 menggunakan Voting Regressor
print(f"\nPenjelasan LIME untuk Prediksi Periode ke-53 (Menggunakan Voting Regressor):")
pred_voting_53_instance = voting_regressor.predict(new_data_53)[0]
print(f"Prediksi Jumlah Tanam Periode 53: {pred_voting_53_instance:.2f}")

exp_53 = explainer.explain_instance(
    data_row=new_data_53.iloc[0].values,
    predict_fn=lambda x: voting_regressor.predict(pd.DataFrame(x, columns=X_train.columns)),
    num_features=len(features)
 )
exp_53.as_list()

fig_53 = exp_53.as_pyplot_figure()
fig_53.set_size_inches(10, 6)
plt.title(f'LIME Explanation for Prediction of Period 53 (Predicted: {pred_voting_53_instance:.2f})')
plt.tight_layout()
plt.show()

